### ISSUE TITLE
Convert MATLAB "Common Components" to Dash

### ISSUE THREAD

**Issue by jackparmer** [plotly/dash_matlab#10]
Please add all Dash conversions for "Common Components" on this page - https://github.com/plotly/dash_matlab/blob/main/ui2dash.m -  to [ui2dash](https://github.com/plotly/dash_matlab/blob/main/ui2dash.m). Most of these components will have close analogues in Dash Core components and Dash HTML components. Please skip/ignore CheckboxTree/NodeTree, ListBox, Spinner, StateButton, ToggleGroup, and Tree/TreeNode, because these do not have analogous components in Dash. Please commit your solution to https://github.com/plotly/dash_matlab as a GitHub pull request and ask Igor review when you are finished.

I recommend making a commonComponents.m here file in the [aux](https://github.com/plotly/dash_matlab/issues/3) folder to keep [ui2dash](https://github.com/plotly/dash_matlab/blob/main/ui2dash.m) easy to read.

**Comment by carlosbionic** [comment]
The "Common Components" needed to be converted are listed on this page:
https://www.mathworks.com/help/matlab/creating_guis/choose-components-for-your-app-designer-app.html

Ignoring CheckboxTree/NodeTree, ListBox, Spinner, StateButton, ToggleGroup, and Tree/TreeNode, (these do not have analogous components in Dash).
