### ISSUE TITLE
New example: stock ticker app

### ISSUE THREAD

**Issue by jackparmer** [plotly/dash_matlab#13]
Please add a new example to the [Examples folder ](https://github.com/plotly/dash_matlab/issues/3) for recreating this Python stock picker Dash app with the MATLAB Dash DSL:

https://twitter.com/plotlygraphs/status/1412117655020969999

**Comment by omarkhater** [comment]
I just added the app here 
https://github.com/plotly/dash_matlab/tree/main/Examples/stock_ticker

**Comment by jackparmer** [comment]
Nice work
