### ISSUE TITLE
Do we need to stop the MATLAB engine in Python?

### ISSUE THREAD

**Issue by jackparmer** [plotly/dash_matlab#2]
The Python MATLAB engine is started here - https://github.com/plotly/dash_matlab/blob/main/updatePlotlyGraphPy.py#L4. Do we need to explicitly stop it? What are the implications of it not being stopped?

**Comment by Igor-gomonov** [comment]
terminating MATLABPyhost or 2nd MATLAB process would close the background matlab session and give back control to main window as before. If dash app is running, second matlab instance must be on too
