### ISSUE TITLE
Improve project file organization

### ISSUE THREAD

**Issue by jackparmer** [plotly/dash_matlab#3]
I would propose 2 folders at the root (along with a README and CHANGELOG) - Examples and Aux. The Examples folder would hold folders of runnable, simple examples taken from dash.plotly.com. These example folders would have at least 3 files - the main app.m file, the callback.py shim file, and the callback.m file. For every callback in a Dash app, there would be a set of one .py and .m callback files.

The Aux folder would hold all helper functions that are hidden from the end user. 

Thoughts?

**Comment by Igor-gomonov** [comment]
Readme should be updated as package expands

**Comment by Igor-gomonov** [comment]
Readme should be updated as package expands
