### ISSUE TITLE
Investigate injecting loading state components into addLayout

### ISSUE THREAD

**Issue by jackparmer** [plotly/dash_matlab#4]
For callbacks that take longer than one second to update the app, need an easy option to add a loading spinner to that component, group of components, or entire app:

https://dash.plotly.com/loading-states

**Comment by carlosbionic** [comment]
Sent a PR for plotlyfig2dash.m. A loading circle appears when loading a new graph, but while loading the graph dissapears. It would be nice if the graph is still visible while loading.

**Comment by jackparmer** [comment]
The graph doesn't appear yet because it's still loading (that's point of having the loading spinner, so you know that the app is not broken even though the graph has not drawn yet). Can you please link the PR here so that we can keep track of progress on this issue!

**Comment by carlosbionic** [comment]
This PR? https://github.com/plotly/dash_matlab/pull/9
